name: 'Deployment'
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
          cache: 'yarn'

      - run: echo "call deployment script here with ssh or use deployment workflows"
