name: 'Deploy to Staging'
on:
  release:
    types: [published]

jobs:
  deploy-staging:
    uses: emnnipal/boilerplate-ts-nodejs/.github/workflows/deploy-workflow.yml@main
    with:
      environment: STAGING
      branch: ${{ github.ref }}
    secrets:
      ssh_host: ${{ secrets.STAGING_HOST }}
      ssh_user: ${{ secrets.USERNAME }}
      ssh_key_ed25519: ${{ secrets.STAGING_KEY_ED25519 }}
      ssh_port: ${{ secrets.PORT }}
