name: 'Manual Deploy to Dev'
on: workflow_dispatch

jobs:
  manual-deploy-dev:
    uses: ./.github/workflows/deploy-workflow.yml
    with:
      environment: DEV
    secrets:
      ssh_host: ${{ secrets.HOST }}
      ssh_user: ${{ secrets.USERNAME }}
      ssh_key_ed25519: ${{ secrets.KEY_ED25519 }}
      ssh_port: ${{ secrets.PORT }}
